#!/bin/bash

filefmt="$1"
findfmt="$2"

for i in $(find ./ -type f | grep "${filefmt}"); do
	catres="$(cat $i | grep -n --color=always "${findfmt}")"
	if [[ -n "$catres" ]]; then
		printf "%s:\n%s\n" "$i" "$catres"
		echo
	fi
done
